### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by Chitransh-M** [cmasch/cnn-text-classification#2]
'glove.6B.300d.txt'
'data/rt-polaritydata/rt-polarity.neg'
'data/rt-polaritydata/rt-polarity.pos'
'data/imdb/train/neg'
'data/imdb/train/pos'
'data/imdb/test/neg'
'data/imdb/test/pos'
'data/yelp/neg.txt'
'data/yelp/pos.txt'

Where is this all files

**Comment by cmasch** [comment]
You can find infos about the required data here: https://github.com/cmasch/cnn-text-classification#evaluation

Please download the datasets from the links given there. I recommend using IMDB.
For using glove, you have to download the embeddings. You can also set `USE_GLOVE=False`, for that you dont need downloading them.

Best
Christopher

**Comment by Ming2018ming** [comment]
Hello, I'm studying NPL recently, and I'm very interested in your code. Would you please provide me with your processed yelp dataset?
